### ISSUE TITLE
ADD A README WITH BUILD SCRIPT

### ISSUE THREAD

**Issue by soulr344** [Exynos-nigg/android_device_samsung_m31nsxx#1]
hi, im too lazy to write `export ALLOW_MISSING_DEPENDENCIES=true && . build/envsetup.sh && lunch omni_m31nsxx-eng && mka recoveryimage -j$(nproc)` so can you add a readme? thanks

**Comment by Exynos-nigg** [comment]
lmao

**Comment by Exynos-nigg** [comment]
ok done lmao


p.s yes i kanged it from urs xD
